title: EnergyTS
page-top-title: Your Partner in Sustainability
top-section-bg-text: Empowering Energy Strategies for a Greener Tomorrow
home-subtitle: About Us
copyright-text: '&copy; Energy Transition &amp; Strategies LTD 2025. All Rights Reserved.'
